<option value="Aceh Besar">Aceh Besar</option>
<option value="Banda Aceh">Banda Aceh</option>
<option value="Bandar Lampung">Bandar Lampung</option>
<option value="Bandung">Bandung</option>
<option value="Banyuwangi">Banyuwangi</option>
<option value="Batu">Batu</option>
<option value="Bekasi">Bekasi</option>
<option value="Bengkulu">Bengkulu</option>
<option value="Biak">Biak</option>
<option value="Bitung">Bitung</option>
<option value="Blitar">Blitar</option>
<option value="Bontang">Bontang</option>
<option value="Bukittinggi">Bukittinggi</option>
<option value="Ciamis">Ciamis</option>
<option value="Cianjur">Cianjur</option>
<option value="Cimahi">Cimahi</option>
<option value="Cirebon">Cirebon</option>
<option value="Cilacap">Cilacap</option>
<option value="Denpasar">Denpasar</option>
<option value="Depok">Depok</option>
<option value="Gorontalo">Gorontalo</option>
<option value="Indramayu">Indramayu</option>
<option value="Jakarta Barat">Jakarta Barat</option>
<option value="Jakarta Pusat">Jakarta Pusat</option>
<option value="Jakarta Selatan">Jakarta Selatan</option>
<option value="Jakarta Timur">Jakarta Timur</option>
<option value="Jakarta Utara">Jakarta Utara</option>
<option value="Jambi">Jambi</option>
<option value="Jember">Jember</option>
<option value="Jepara">Jepara</option>
<option value="Karawang">Karawang</option>
<option value="Kediri">Kediri</option>
<option value="Kendari">Kendari</option>
<option value="Langsa">Langsa</option>
<option value="Lumajang">Lumajang</option>
<option value="Magelang">Magelang</option>
<option value="Malang">Malang</option>
<option value="Manado">Manado</option>
<option value="Madiun">Madiun</option>
<option value="Majalengka">Majalengka</option>
<option value="Metro">Metro</option>
<option value="Mojokerto">Mojokerto</option>
<option value="Mataram">Mataram</option>
<option value="Minahasa">Minahasa</option>
<option value="Nabire">Nabire</option>
<option value="Palangkaraya">Palangkaraya</option>
<option value="Padang">Padang</option>
<option value="Palembang">Palembang</option>
<option value="Palu">Palu</option>
<option value="Pangandaran">Pangandaran</option>
<option value="Pekalongan">Pekalongan</option>
<option value="Pekanbaru">Pekanbaru</option>
<option value="Ponorogo">Ponorogo</option>
<option value="Probolinggo">Probolinggo</option>
<option value="Purwokerto">Purwokerto</option>
<option value="Salatiga">Salatiga</option>
<option value="Samarinda">Samarinda</option>
<option value="Serang">Serang</option>
<option value="Situbondo">Situbondo</option>
<option value="Solo (Surakarta)">Solo (Surakarta)</option>
<option value="Subang">Subang</option>
<option value="Surabaya">Surabaya</option>
<option value="Tasikmalaya">Tasikmalaya</option>
<option value="Tangerang">Tangerang</option>
<option value="Tegal">Tegal</option>
<option value="Tarakan">Tarakan</option>
<option value="Timika">Timika</option>
<option value="Wamena">Wamena</option>
<option value="Yogyakarta">Yogyakarta</option>
